---
- name: Set include path for stratum1
  set_fact:
    eessi_stratum1_include_path: "{{ role_path }}/variables"

- name: Gather EESSI stratum1 variables
  include_vars: "{{ eessi_stratum1_include_path }}/main.yml"

- debug:
   msg: "CVMFS role: {{ cvmfs_role }}"

- include_role: 
    name: eessi.roles/roles/cvmfs
